### ISSUE TITLE
About the role of parameters

### ISSUE THREAD

**Issue by ZhenChen008** [chelaxe/SwingingDoor#4]
Hello, I am interested in this project, can I ask a question：what are the functions of the following parameters?
especially the last two👀
>def swinging_door(  # pylint: disable=too-many-locals
    data,  # type: List[Point]
    deviation=0.1,  # type: float
    mode=False,  # type: bool
    step=10,  # type: int
):

**Comment by chelaxe** [comment]
Hello. The meaning of the following parameters is:

- data - list of points (x - time, y - time value)
- deviation - the error we allow
- mode - whether to use the algorithm modified by me, otherwise the classic implementation
- step - if mode = True, the step of the guaranteed value is necessary when the value fluctuates in one range, so that there is no silence on the air after the filter.

**Comment by ZhenChen008** [comment]
Very useful explanation, thanks. I also have another question: Your improvement on this algorithm mainly means that you can set the step size to improve performance?

**Comment by chelaxe** [comment]
Setting the step is necessary to ensure that data is received through the step value. This behavior is useful for less dynamic data.
